spring.application.name=list
#spring.datasource.url=185.167.96.131
#spring.datasource.username=root
#spring.datasource.password=zaq1@WSX3edc4rfv
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Spring Security
jwt.access-secret-key=ElFPdpDC2qahkOyQWIVPqnh1y1O6lJAQ
jwt.access-token-validity-in-min=15
jwt.refresh-secret-key=GfrKsZCgBcmZBPLWfD9jFUQ7z1X9V1GC
jwt.refresh-token-validity-in-min=120


# Testing db
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# MySQL db
spring.datasource.url=jdbc:mysql://185.167.96.131:3306;databaseName=moja_baza;encrypt=true;trustServerCertificate=true;
spring.datasource.username=root
spring.datasource.password=zaq1@WSX3edc4rfv
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect