spring.application.name=list

# Spring Security
jwt.access-secret-key=ElFPdpDC2qahkOyQWIVPqnh1y1O6lJAQ
jwt.access-token-validity-in-min=15
jwt.refresh-secret-key=GfrKsZCgBcmZBPLWfD9jFUQ7z1X9V1GC
jwt.refresh-token-validity-in-min=120


# Testing db
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console